version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: occupancy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  forecast:
    build:
      context: .
      dockerfile: docker/forecast.Dockerfile
    environment:
      PORT: 8000
    volumes:
      - ./services/forecast/app:/app/app:ro
    ports:
      - "8000:8000"
    depends_on: [postgres, redis]

  gateway:
    build:
      context: .
      dockerfile: docker/gateway.Dockerfile
    environment:
      FORECAST_URL: http://forecast:8000
      KAFKA_BROKERS: kafka:29092
      REDIS_ADDR: redis:6379
      POSTGRES_DSN: postgres://postgres:postgres@postgres:5432/occupancy?sslmode=disable
    ports:
      - "8080:8080"
    depends_on: [forecast, kafka, postgres, redis]

  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on: [gateway]

  ingest:
    image: golang:1.22
    working_dir: /workspace/services/ingest
    command: >
      bash -lc "go run cmd/ingest/main.go
      -mode=csv
      -csv ../../dbt_occupancy/seeds/gym_dataset.csv
      -speed=120
      -device=gym-door-1"
    environment:
      KAFKA_BROKERS: kafka:29092
    volumes:
      - .:/workspace:ro
    depends_on: [kafka]

volumes:
  pgdata:
